# Generated by Django 3.0.4 on 2020-03-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('1', 'Teacher'), ('2', 'HM'), ('3', 'Block Admin'), ('4', 'District Admin'), ('5', 'State Admin')], default='1', max_length=1)),
                ('msg_head', models.CharField(max_length=30)),
                ('msg_body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_notif.Users')),
            ],
        ),
    ]
