# Generated by Django 3.0.4 on 2020-03-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_notif.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'HM'), ('3', 'Block Admin'), ('4', 'District Admin'), ('5', 'State Admin')], default='1', max_length=1),
        ),
    ]
