# Generated by Django 3.0.4 on 2020-03-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notif', '0002_auto_20200323_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
