# Generated by Django 3.0.4 on 2020-03-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('push_notif', '0003_auto_20200323_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('1', 'Teacher'), ('2', 'HM'), ('3', 'Block Admin'), ('4', 'District Admin'), ('5', 'State Admin')], default='1', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
