# Generated by Django 3.0.4 on 2020-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notif', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('1', 'Teacher'), ('2', 'HM'), ('3', 'Block Admin'), ('4', 'District Admin'), ('5', 'State Admin')], default='1', max_length=1)),
                ('msg_head', models.CharField(max_length=30)),
                ('msg_body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
