# Generated by Django 3.0.5 on 2020-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notif', '0005_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=100)),
            ],
        ),
    ]
